server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://babar.db.elephantsql.com:5432/rwfbzojd?socketTimeout=3
    username: rwfbzojd
    password: 5-qQ8taLe1hVNmFvXNbjDvywY0h9si5B
    driverClassName: org.postgresql.Driver